var formSchema = {
  "formName": "Record Registration Form",
  "components": [
    {
      "label": "HTML",
      "tag": "h4",
      "className": "",
      "attrs": [
        {
          "attr": "",
          "value": ""
        }
      ],
      "content": "Record Registration",
      "refreshOnChange": false,
      "customClass": "",
      "hidden": false,
      "modalEdit": false,
      "key": "html",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "htmlelement",
      "dataGridLabel": false,
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "id": "ev458ec"
    },
    {
      "label": "Date",
      "labelPosition": "top",
      "displayInTimezone": "viewer",
      "useLocaleSettings": false,
      "allowInput": true,
      "format": "yyyy-MM-dd hh:mm a",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "shortcutButtons": [],
      "enableDate": true,
      "datePicker": {
        "disable": "",
        "disableFunction": "",
        "disableWeekends": false,
        "disableWeekdays": false,
        "minDate": null,
        "maxDate": null,
        "showWeeks": true,
        "startingDay": 0,
        "initDate": "",
        "minMode": "day",
        "maxMode": "year",
        "yearRows": 4,
        "yearColumns": 5
      },
      "enableTime": true,
      "timePicker": {
        "showMeridian": true,
        "hourStep": 1,
        "minuteStep": 1,
        "readonlyInput": false,
        "mousewheel": true,
        "arrowkeys": true
      },
      "multiple": false,
      "defaultValue": "",
      "defaultDate": "",
      "customOptions": {},
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "enableMinDateInput": false,
      "enableMaxDateInput": false,
      "unique": false,
      "validateWhenHidden": false,
      "errorLabel": "",
      "errors": "",
      "key": "date",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "datetime",
      "timezone": "",
      "dataGridLabel": false,
      "input": true,
      "prefix": "",
      "suffix": "",
      "refreshOn": "",
      "widget": {
        "type": "calendar",
        "displayInTimezone": "viewer",
        "locale": "en",
        "useLocaleSettings": false,
        "allowInput": true,
        "mode": "single",
        "enableTime": true,
        "noCalendar": false,
        "format": "yyyy-MM-dd hh:mm a",
        "hourIncrement": 1,
        "minuteIncrement": 1,
        "time_24hr": false,
        "minDate": null,
        "disabledDates": "",
        "disableWeekends": false,
        "disableWeekdays": false,
        "disableFunction": "",
        "maxDate": null
      },
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "datepickerMode": "day",
      "id": "enpgyim"
    },
    {
      "label": "Emp ID",
      "labelPosition": "top",
      "placeholder": "Emp ID",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "applyMaskOn": "change",
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "delimiter": false,
      "requireDecimal": false,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "min": "",
        "max": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "step": "any",
        "integer": ""
      },
      "validateWhenHidden": false,
      "errorLabel": "",
      "errors": "",
      "key": "empId",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "number",
      "dataGridLabel": false,
      "input": true,
      "unique": false,
      "refreshOn": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "id": "eywvu0j",
      "defaultValue": null
    },
    {
      "label": "Emp Name",
      "customDropdown": "",
      "myCustomSetting": "",
      "labelPosition": "top",
      "placeholder": "Emp Name",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "displayMask": "",
      "applyMaskOn": "change",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "type": "textfield",
      "dataGridLabel": false,
      "input": true,
      "key": "textField",
      "unique": false,
      "refreshOn": "",
      "errorLabel": "",
      "attributes": {},
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
        "minLength": "",
        "maxLength": "",
        "pattern": ""
      },
      "conditional": {
        "show": null,
        "when": null,
        "eq": ""
      },
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "properties": {},
      "addons": [],
      "inputType": "text",
      "id": "ewbikn",
      "defaultValue": ""
    },
    {
      "label": "Deployment",
      "labelPosition": "top",
      "optionsLabelPosition": "right",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "inline": true,
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "dataSrc": "values",
      "values": [
        {
          "label": "Personal",
          "value": "personal",
          "shortcut": ""
        },
        {
          "label": "Accounting",
          "value": "accounting",
          "shortcut": ""
        },
        {
          "label": "Development",
          "value": "development",
          "shortcut": ""
        },
        {
          "label": "Human Resource",
          "value": "humanResource",
          "shortcut": ""
        },
        {
          "label": "Growth of Affairs",
          "value": "growthOfAffairs",
          "shortcut": ""
        }
      ],
      "dataType": "",
      "valueProperty": "",
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "onlyAvailableItems": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "validateWhenHidden": false,
      "errorLabel": "",
      "errors": "",
      "key": "deployment",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "radio",
      "dataGridLabel": false,
      "data": {
        "url": ""
      },
      "template": "<span>{{ item.label }}</span>",
      "authenticate": false,
      "ignoreCache": false,
      "redrawOn": "",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "unique": false,
      "refreshOn": "",
      "widget": null,
      "validateOn": "change",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "inputType": "radio",
      "fieldSet": false,
      "id": "eas03y",
      "defaultValue": ""
    },
    {
      "label": "Attendance Status",
      "labelPosition": "top",
      "widget": "choicesjs",
      "placeholder": "Attendance Status",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "uniqueOptions": false,
      "autofocus": false,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "dataSrc": "values",
      "data": {
        "values": [
          {
            "label": "Normal Duty",
            "value": "normalDuty"
          },
          {
            "label": "Day Duty",
            "value": "dayDuty"
          },
          {
            "label": "Night Duty",
            "value": "nightDuty"
          }
        ],
        "resource": "",
        "url": "",
        "json": "",
        "custom": ""
      },
      "dataType": "",
      "idPath": "id",
      "valueProperty": "",
      "template": "<span>{{ item.label }}</span>",
      "refreshOn": "",
      "refreshOnBlur": "",
      "clearOnRefresh": false,
      "searchEnabled": true,
      "selectThreshold": 0.3,
      "readOnlyValue": false,
      "customOptions": {},
      "useExactSearch": false,
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "onlyAvailableItems": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "validateWhenHidden": false,
      "errorLabel": "",
      "errors": "",
      "key": "attendanceStatus",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "select",
      "indexeddb": {
        "filter": {}
      },
      "dataGridLabel": false,
      "lazyLoad": true,
      "selectFields": "",
      "searchField": "",
      "searchDebounce": 0.3,
      "minSearch": 0,
      "filter": "",
      "limit": 100,
      "authenticate": false,
      "ignoreCache": false,
      "redrawOn": "",
      "input": true,
      "prefix": "",
      "suffix": "",
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "fuseOptions": {
        "include": "score",
        "threshold": 0.3
      },
      "id": "eco1d4e",
      "defaultValue": ""
    },
    {
      "label": "Attendance Time",
      "pickerType": "datetimepicker",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "autofocus": false,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validate": {
        "required": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "validateWhenHidden": false,
      "validateOn": "change",
      "errorLabel": "",
      "errors": "",
      "key": "extendeddatepicker",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "extendeddatepicker",
      "dataGridLabel": false,
      "input": true,
      "prefix": "",
      "suffix": "",
      "refreshOn": "",
      "widget": null,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "enableTypeSelector": true,
      "id": "ezm42",
      "defaultValue": null
    },
    {
      "label": "Comment",
      "labelPosition": "top",
      "placeholder": "Comment",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "applyMaskOn": "change",
      "editor": "",
      "autoExpand": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "html",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "minWords": "",
        "maxWords": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "validateWhenHidden": false,
      "errorLabel": "",
      "errors": "",
      "key": "comment",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textarea",
      "rows": 3,
      "wysiwyg": false,
      "dataGridLabel": false,
      "input": true,
      "refreshOn": "",
      "allowMultipleMasks": false,
      "addons": [],
      "mask": false,
      "inputType": "text",
      "inputMask": "",
      "fixedSize": true,
      "id": "efizm9c",
      "defaultValue": ""
    },
  //   {
  //     "label": "Submit",
  //     "action": "submit",
  //     "showValidations": false,
  //     "theme": "primary",
  //     "size": "md",
  //     "block": false,
  //     "leftIcon": "",
  //     "rightIcon": "",
  //     "shortcut": "",
  //     "description": "",
  //     "tooltip": "",
  //     "customClass": "",
  //     "tabindex": "",
  //     "disableOnInvalid": false,
  //     "hidden": false,
  //     "autofocus": false,
  //     "disabled": false,
  //     "tableView": false,
  //     "modalEdit": false,
  //     "key": "submit",
  //     "tags": [],
  //     "properties": {},
  //     "conditional": {
  //         "show": null,
  //         "when": null,
  //         "eq": "",
  //         "json": ""
  //     },
  //     "customConditional": "",
  //     "logic": [],
  //     "attributes": {},
  //     "overlay": {
  //         "style": "",
  //         "page": "",
  //         "left": "",
  //         "top": "",
  //         "width": "",
  //         "height": ""
  //     },
  //     "type": "button",
  //     "hideLabel": false,
  //     "input": true,
  //     "placeholder": "",
  //     "prefix": "",
  //     "suffix": "",
  //     "multiple": false,
  //     "defaultValue": null,
  //     "protected": false,
  //     "unique": false,
  //     "persistent": false,
  //     "clearOnHide": true,
  //     "refreshOn": "",
  //     "redrawOn": "",
  //     "dataGridLabel": true,
  //     "labelPosition": "top",
  //     "errorLabel": "",
  //     "dbIndex": false,
  //     "customDefaultValue": "",
  //     "calculateValue": "",
  //     "calculateServer": false,
  //     "widget": {
  //         "type": "input"
  //     },
  //     "validateOn": "change",
  //     "validate": {
  //         "required": false,
  //         "custom": "",
  //         "customPrivate": false,
  //         "strictDateValidation": false,
  //         "multiple": false,
  //         "unique": false
  //     },
  //     "allowCalculateOverride": false,
  //     "encrypted": false,
  //     "showCharCount": false,
  //     "showWordCount": false,
  //     "allowMultipleMasks": false,
  //     "addons": [],
  //     "id": "e5evoze"
  // }
  ]
}
var languageSupport= {};